In [152]:
q=10

In [153]:
print("hello")

hello


In [154]:
print("how are you")

how are you


In [155]:
def hello():
    print("hello how are you")

In [156]:
hello()

hello how are you


In [157]:
a=12
b=45
print(a+b)

57


In [158]:
import numpy as np

np.random.rand(5)

array([0.10340034, 0.54144067, 0.85549132, 0.14933138, 0.6412194 ])

In [159]:
np.random.randint(10,20,10)

array([13, 18, 17, 11, 17, 13, 18, 19, 15, 14])

In [160]:
# array attribute
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
arr.shape

(3, 3)

In [162]:
arr.size

9

In [163]:
arr.dtype

dtype('int32')

In [164]:
#array method
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [165]:
arr.min()

1

In [166]:
arr.max()

9

In [167]:
arr.sum()

45

In [168]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [169]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [170]:
arr.mean()

5.0

In [171]:
arr.std()

2.581988897471611

In [172]:
arr.argmax()

8

In [173]:
arr.argmin()

0

In [174]:
#reshaping and resiging


In [175]:
arr = np.arange(1,31)

In [176]:
arr =arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [177]:
#NUMPY INDEXING AND SLICING OF VECTORS


In [178]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [179]:
arr[3::2]

array([14, 16, 18, 20])

In [180]:
arr[9]

20

In [181]:
#NUMPY INDEXING AND SLICING OF MATRIX

In [182]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [187]:
arr[0,2]

3